### ISSUE TITLE
Wrong scores in polish scrabble for letters "ż" and "ź"

### ISSUE THREAD

**Issue by Kyczan** [kamilmielnik/scrabble-solver#115]
Hi!

Please switch these scores:
`ż` has 9 and should have 5
`ź` has 5 and should have 9

https://github.com/kamilmielnik/scrabble-solver/blob/96c2953aee6495cfeda564849d6256cc07c6afe8/packages/configs/src/scrabble/tiles/tilesPl.ts#L32

**Comment by kamilmielnik** [comment]
Thank you for the report!
Would you like to file a PR?

**Comment by Kyczan** [comment]
Sure, will do.

**Comment by kamilmielnik** [comment]
Released in [2.4.9](https://github.com/kamilmielnik/scrabble-solver/releases/tag/2.4.9) and deployed :heavy_check_mark:
