### ISSUE TITLE
I cannot build @scrabble-solver

### ISSUE THREAD

**Issue by Glairly** [kamilmielnik/scrabble-solver#136]
Hi kamilmielnik! I'm a student from KMITL majoring in Computer Engineering. As I want to use your repository for educational purposes for my mini-project, I just cloned your repo and tried to build and run them. but I got this errors
![image](https://user-images.githubusercontent.com/62894559/190094696-6a594b41-4ddb-4334-9439-202692a4b8d4.png)

Could you please help me solve this?
Thank you in advance.

This my node version
![image](https://user-images.githubusercontent.com/62894559/190094990-8e995630-d0dd-4474-86c5-36dfea4475c1.png)

**Comment by Glairly** [comment]
Hi kamilmielnik!  I'm a student from KMITL majoring in Computer Engineering. As I want to use your repository for educational purposes for my mini-project, I just cloned your repos and tried to build and run them. but I got this errors 
![image](https://user-images.githubusercontent.com/62894559/190094382-faa9ba6f-17fa-43b9-bb1a-f9e6447543c5.png)

Could you please help me solve this?

**Comment by Glairly** [comment]
it seems to happen only on my laptop. my friend gets it working well. I'll close the issue but if you have any solution feel free to describe it. 
anyway thank you.

**Comment by kamilmielnik** [comment]
@Glairly

1. I see you're using `yarn`. Does it work for you with `npm`?
2. Judging from error messages you need to run `npm install` first.

โชคดีครับ

**Comment by Glairly** [comment]
1. I also got this error while using npm too.
2. I already run it. I even re-clone and do everything from the start here is the step. By running ```npm install && npm run install:dev``` at the root. It seem lerna bootstrap is working fine but when it's time to build I alway got this error .

**Comment by kamilmielnik** [comment]
> but when it's time to build I alway got this error .

From the fist screenshot I can see that you're running `yarn build` in `packages/scrabble-solver` - this won't work due to lerna.
`yarn build` (or `npm run build`) needs to be executed in the root directory of the project (i.e. `C:\Users\USER\Desktop\grade16\AI\scrabble-solver`) - the same place where you run `npm install && npm run install:dev`.

Does this help?

----

If you want to build a single package, you can run e. g. `lerna run build --scope=@scrabble-solver/constants` from the root directory of the project.

**Comment by Glairly** [comment]
I've try running ```npm run start``` in the root still got  which will cause lerna to build all the packages and serve the app right? And I still got this error. 
I've did some research this error cause by nextjs v10.0.5 and they recommend me to upgrade it.it's worked But it broke all the code.

**Comment by Glairly** [comment]
it's worked!!!  🚀🚀🚀 
Thank you for your hard work sir.
