### ISSUE TITLE
Missing packages?

### ISSUE THREAD

**Issue by ericgjackson** [kamilmielnik/scrabble-solver#168]
[Came across your repo from Hacker News.  Like what you've built.]

I had to install a bunch of additional packages to get things to run:

env-cmd
npm-run-all
next
workbox-webpack-plugin
react-redux
@reduxjs/toolkit
redux
redux-saga
store2
classnames
react-modal
react-use
react-popper
react-portal
react-window
workbox-window

Was I missing some step that would have installed everything I needed more simply?

**Comment by kamilmielnik** [comment]
> Was I missing some step that would have installed everything I needed more simply?

Running `npm install` in the root repository is enough to get all dependencies installed (in handles sub-packages as well, thanks to [postinstall](https://github.com/kamilmielnik/scrabble-solver/blob/master/package.json#L47) script). To make project runnable locally you just need to build all the sub-packages.

To sum up, running these 2 commands in the root folder of a freshly cloned repository should be sufficient:
```Shell
npm install
npm run install:dev
```

**Comment by kamilmielnik** [comment]
I've [added](https://github.com/kamilmielnik/scrabble-solver/commit/cb8f422ba009e8778d679c172ab7730931a97aa9) some instructions to README: https://github.com/kamilmielnik/scrabble-solver#develop

I hope it helps!

**Comment by ericgjackson** [comment]
Thanks, that worked.
