### ISSUE TITLE
Unable to input Spanish digraph tiles

### ISSUE THREAD

**Issue by jmontane** [kamilmielnik/scrabble-solver#279]
Hi,

I'm testing scrabble-solver, and I'm unable to input Spanish digraph (2 letters) tiles at rack using keyboard. I was able to set digraph pasting LL and CH from clipboard only.

Is there any way to input such tiles typing?

**Comment by kamilmielnik** [comment]
Hello,

It's a bug.
There used to be a way (<kbd>Ctrl</kbd> + <kbd>C</kbd> / <kbd>Ctrl</kbd> + <kbd>R</kbd> / <kbd>Ctrl</kbd> + <kbd>L</kbd>) but I ... accidentally deleted it 😶‍🌫️ 

Thank you for the report!
I'll try to bring it back this week.

**Comment by kamilmielnik** [comment]
Fixed by 1c5bcca511363cda036b947a7d5a20a2fcdbfc8f, v2.11.8 released.
