### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by kamilmielnik** [kamilmielnik/scrabble-solver#289]
Notice how "K" looks like on the board. This happens sometimes, randomly, but consistently (once it happens for a given result, it will always happen to it). Looks like browser bug.

![image](https://user-images.githubusercontent.com/6830683/230209778-1adea6ff-9118-40a4-a40a-6c66551198e0.png)

**Comment by kamilmielnik** [comment]
Computed `background-color` of a `Tile` is `rgba(0, 0, 0, 0)`.

Color set via styles is correct.

Could this be because of default `background-color: transparent`

**Comment by cristian-po** [comment]
Share the scenario and i will test on different browsers.

**Comment by kamilmielnik** [comment]
Unfortunately I don't have deterministic reproduction steps.
I think switching between OS windows may be a factor, which hints at it being a browser bug.

This happens on Chrome.

**Comment by kamilmielnik** [comment]
Can't reproduce anymore on Chrome Version 124.0.6367.118 (Official Build) (64-bit)
