### ISSUE TITLE
App crashes when changing game type

### ISSUE THREAD

**Issue by kamilmielnik** [kamilmielnik/scrabble-solver#305]
![image](https://user-images.githubusercontent.com/6830683/233706519-b9b59437-ace2-41fa-896b-a158e5cd0943.png)

1. Select GB language
2. Select Super Scrabble
3. Type in the bottom right corner of the board
4. Select Polish

App crashes

**Comment by cristian-po** [comment]
More testing done:
3. It happens if you type in any field of the board.
4. It happens also for Romanian language
