### ISSUE TITLE
Incomplete French dictionary

### ISSUE THREAD

**Issue by JulienGery** [kamilmielnik/scrabble-solver#309]
Hello,
I tried out your Scrabble Solver, and it seems that your dictionary lacks some words, such as "biwa" or "kale(s)."
The dictionary i'm using can be found on this [repo](https://github.com/Thecoolsim/French-Scrabble-ODS8).
Overall, it's really cool!

**Comment by kamilmielnik** [comment]
> Hello, I tried out your Scrabble Solver, and it seems that your dictionary lacks some words, such as "biwa" or "kale(s)." The dictionary i'm using can be found on this [repo](https://github.com/Thecoolsim/French-Scrabble-ODS8).

This is great, thank you @JulienGery! 
I used that repository and released new `scrabble-solver@2.12.5`. Enjoy!

----

![image](https://github.com/kamilmielnik/scrabble-solver/assets/6830683/4a28f2c6-afea-4492-9219-a6035d1852ee)

Closed by 3c378a181e069658da0449ffa6f96a498e2a22c3
