### ISSUE TITLE
Display board coordinates

### ISSUE THREAD

**Issue by kamilmielnik** [kamilmielnik/scrabble-solver#312]
>  See attached how the board looks like in romanian scrabble ( while in english is exactly the opposite, letters on columns and numbers on rows ).

> Thinking now about the coordinates, I have a better idea. Can you add in settings a switch for coordinares to choose from 2 types of board:
> - letters on columns and numbers on rows
> - numbers on columns and letters on rows

Related PR: #315

**Comment by cristian-po** [comment]
See attached the visual of the 2 boards.
![lettersoncolumns](https://github.com/kamilmielnik/scrabble-solver/assets/149695319/e23e090e-a334-4727-b7bc-4c9d25a76fdb)
![numbersoncolumns](https://github.com/kamilmielnik/scrabble-solver/assets/149695319/ddcf5fe2-cf17-4612-9c09-2ee283fa0ee7)

**Comment by nicolescucosti** [comment]
Hello! I started to look on it. Adding the coordinates to the board.

**Comment by kamilmielnik** [comment]
@cristian-po released in 2.13.5, enjoy!

![image](https://github.com/kamilmielnik/scrabble-solver/assets/6830683/cc5710d2-2f4c-448a-9fcb-e9a389c8b625)
