### ISSUE TITLE
Coordinates column displaying in the 'possible solutions' section

### ISSUE THREAD

**Issue by cristian-po** [kamilmielnik/scrabble-solver#322]
Hi Kamil,

I would like to have an extra column added in the 'possible solutions' section ( upper right section of the screen ) and be named 'Coordinates' and placed as the first column in the table.
The value in the column coordinates will be a combination of the left coordinate on the board and the upper coordinate on the board with the following logic:

- if the word is placed horizontally the coordinate will be <left value> <upper value>
- if the word is placed vertically the coordinate will be <upper value> <left value>

Could you please also add the tag 'must have' ?
Thank you.

Example:
Horizontal word. Coordinates are H4
![horizontal word](https://github.com/kamilmielnik/scrabble-solver/assets/149695319/2f3e9ff3-500f-4a1a-abae-3828f4a2f65b)

Vertical word. Coordinates are 8D
![vertical word](https://github.com/kamilmielnik/scrabble-solver/assets/149695319/0c35d0c4-9de4-4189-8697-f798dca3cbe6)

**Comment by kamilmielnik** [comment]
@cristian-po released in 2.13.7, enjoy!
