### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by MakuSensei** [kamilmielnik/scrabble-solver#98]
hi i just found this project and it looks interesting. but since I don't manage Spanish I won't be able to use it. So I would ask if you can add the FISE 2017 dictionary

greetings from Argentina

**Comment by kamilmielnik** [comment]
Hi @MakuSensei !

It would be great to support Spanish! 
But I don't know Spanish so I'm going to need your help.

1. Could you please provide a link to download this FISE 2017 dictionary that you mentioned?
2. We should also add Spanish translations in UI. Could you please translate this file to Spanish: https://github.com/kamilmielnik/scrabble-solver/blob/master/packages/scrabble-solver/src/i18n/en.json?

**Comment by MakuSensei** [comment]
I will be happy to translate it. I do not assure you that it will be fast but when I am with time I will. I do not know much about github so I do not know what steps I should do.

**Comment by kamilmielnik** [comment]
>  I do not know much about github so I do not know what steps I should do.

@MakuSensei don't worry about it, if you paste it here in a comment that's fine too :+1:

**Comment by MakuSensei** [comment]
thanks i will do that when i start to translate it

**Comment by MakuSensei** [comment]
{
  "cell.set-blank": "Mark it a blank",
  "cell.set-not-blank": "Mark it not a blank",
  "cell.toggle-direction": "Typing direction - click to toggle",
  "common.blanks": "Blancos",
  "common.clear": "Borrar",
  "common.close": "Cerrar",
  "common.consonants": "Consonantes",
  "common.loading": "Cargando",
  "common.points": "Puntos",
  "common.tiles": "Longitud",
  "common.vowels": "Vocales",
  "common.word": "Palabra",
  "common.words": "Palabras",
  "dictionary.empty-state.no-definitions": "La palabra existe en el diccionario pero no tiene una definición.",
  "dictionary.empty-state.no-results": "No se puede encontrar la definición de palabra en el diccionario.",
  "dictionary.empty-state.not-allowed": "Esta palabra no es aceptable según es.wiktionary.org.",
  "dictionary.empty-state.uninitialized": "Aquí se mostrará la definición del diccionario de la última palabra resaltada.",
  "empty-state.error": "Error",
  "empty-state.info": "Informasion",
  "empty-state.success": "Sí!",
  "empty-state.warning": "Vaya!",
  "github": "Ver este proyecto en GitHub",
  "keyMap": "Atajos de teclado",
  "keyMap.board": "Tablero",
  "keyMap.board.toggle-blank": "Marcar / desmarcar un espacio en blanco",
  "keyMap.board.toggle-direction": "Alternar dirección de escritura",
  "keyMap.board-and-rack": "Tablero y estante",
  "keyMap.board-and-rack.navigate": "Navegar",
  "keyMap.board-and-rack.remove-tile": "Quitar Letra",
  "keyMap.board-and-rack.submit": "Empezar a resolver",
  "keyMap.rack": "Espacio en Blanco",
  "keyMap.rack.insert-blank": "Insertar espacio en blanco (barra espaciadora)",
  "rack.placeholder": "Letras",
  "remaining-tiles": "Casillas Restantes",
  "results.empty-state.outdated": "Los resultados están desactualizados. Haga clic a continuación para actualizar.",
  "results.empty-state.no-results": "No hay resultados; no se pueden generar palabras",
  "results.empty-state.uninitialized": "Aquí se mostrarán las palabras generadas a partir de sus letras.",
  "results.solve": "Resolver",
  "settings": "Configuración",
  "settings.autoGroupTiles": "Agrupar casillas restantes",
  "settings.autoGroupTiles.left": "A la izquierda",
  "settings.autoGroupTiles.right": "A la derecha",
  "settings.autoGroupTiles.null": "No agrupar",
  "settings.game": "Juego",
  "settings.language": "Idioma"
}

**Comment by MakuSensei** [comment]
hello, i still haven't found a link to download the fise 2017 dictionary.
as soon as I find it I'll give it to you

**Comment by kamilmielnik** [comment]
Thank you for the translations!

----

> hello, i still haven't found a link to download the fise 2017 dictionary.

I've learned that another name for "FISE 2017" is "FISE 2".

Here's what I found:
- [LEXICÓN FISE 2 - LISTAS.zip](https://groups.google.com/group/scrabblerosario/attach/966367140bcda/LEXIC%C3%93N%20FISE%202%20-%20LISTAS.zip?part=0.1) (file found in [Google Groups](https://groups.google.com/g/scrabblerosario/c/m2DQCQMLzlw))

@MakuSensei can you please confirm whether its complete?

----

I did some research and it seems that Spanish Scrabble comes with something that is not currently supported: double-letter tiles (LL, RR, CH).
This makes adding Spanish more difficult than other languages added so far.
It's mainly a UI challenge.

**Comment by MakuSensei** [comment]
> Thank you for the translations!
> 
> > hello, i still haven't found a link to download the fise 2017 dictionary.
> 
> I've learned that another name for "FISE 2017" is "FISE 2".
> 
> Here's what I found:
> 
> * [LEXICÓN FISE 2 - LISTAS.zip](https://groups.google.com/group/scrabblerosario/attach/966367140bcda/LEXIC%C3%93N%20FISE%202%20-%20LISTAS.zip?part=0.1) (file found in [Google Groups](https://groups.google.com/g/scrabblerosario/c/m2DQCQMLzlw))
> 
> @MakuSensei can you please confirm whether its complete?
> 
> I did some research and it seems that Spanish Scrabble comes with something that is not currently supported: double-letter tiles (LL, RR, CH).
> This makes adding Spanish more difficult than other languages added so far.
> It's both UI and algorithmic challenge.

exactly contains the words in Spanish.

**Comment by kamilmielnik** [comment]
FISE dictionary is ready :tada: : https://github.com/kamilmielnik/fise-2

I have a plan how to solve this double-letter tiles problem.
But it's going to take some time.

I hope I'll eventually get there :)

**Comment by kamilmielnik** [comment]
@MakuSensei Spanish is now supported :tada: New version is live at https://scrabble-solver.kamilmielnik.com/

If you find any bugs or if you have any ideas for improvement - please create a new issue :pray:
Cheers!

**Comment by MakuSensei** [comment]
> @MakuSensei Spanish is now supported 🎉 New version is live at https://scrabble-solver.kamilmielnik.com/
> 
> If you find any bugs or if you have any ideas for improvement - please create a new issue 🙏
> Cheers!

muchas gracias :D

**Comment by ninel** [comment]
> @MakuSensei Spanish is now supported 🎉 New version is live at https://scrabble-solver.kamilmielnik.com/

Kamil, your Spanish dictionary is incomplete. All verbs need to be expanded through all their conjugated forms (and all their tenses. The FISE dictionary only includes the infinitive form for all verbs. This github project claims to be able to conjugate Spanish verbs: https://github.com/ehoogerbeets/conjugator

**Comment by kamilmielnik** [comment]
Thank you @ninel !

I've updated the dictionary: https://raw.githubusercontent.com/kamilmielnik/fise-2/master/fise-2.txt
And Scrabble Solver uses the updated dictionary now :tada: 

I have not figured out what the digits in some words mean (see [beginning of the file](https://raw.githubusercontent.com/kamilmielnik/fise-2/master/fise-2.txt), e.g. `1a1a` or `1a1iguismos`) - any ideas?

**Comment by kamilmielnik** [comment]
Thank you @ninel ! :100: 

[Now the Spanish dictionary is truly complete](https://github.com/kamilmielnik/fise-2/commit/23544068115a4af724beed9653d7be092ce590fb).

I've updated the dictionary at https://scrabble-solver.kamilmielnik.com/ as well.
